[project]
name = "dumbjared-backend"
version = "0.1.0"
description = "Django backend for Dumb Jared that provides a REST API and handles web scraping."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "django>=5.2.7",
    "django-environ>=0.12.0",
    "django-health-check>=3.20.0",
    "django-unfold>=0.75.0",
    "djangorestframework>=3.16.1",
    "fake-useragent>=2.2.0",
    "playwright>=1.55.0",
    "psycopg[binary]>=3.2.10",
    "requests>=2.32.5",
]

[tool.coverage.run]
omit = [
    "*/migrations/*",
    "*/tests/*",
    "*/__init__.py",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["test_*.py"]
addopts = ["--cov=api", "--cov=core", "--cov=scraper"]

[dependency-groups]
dev = [
    "model-bakery>=1.21.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-django>=4.11.1",
]
prod = [
    "gunicorn>=23.0.0",
    "hiredis>=3.3.0",
    "redis>=7.0.1",
]
